Name         : kde5-systemsettings
Version      : 4.97.0
Release      : 1
Group        : System/Base
License      : GPLv2+
Summary      : KDE System Settings application
Description  : |
  KDE System Settings application
URL          : http://www.kde.org
SetupOptions : -q -n %{name}-%{version}/upstream

Sources:
    - "%{name}-%{version}.tar.xz"

RpmLintIgnore:
    - devel-file-in-non-devel-package
    - no-changelogname-tag
    - library-without-ldconfig-postin
    - library-without-ldconfig-postun

Configure    : none
Builder      : none

PkgBR:
    - kde5-rpm-macros
    - extra-cmake-modules
    - qt5-tools
    - kf5-umbrella
    - kf5-kitemviews-devel
    - kf5-kcmutils-devel
    - kf5-ki18n-devel
    - kf5-kio-devel
    - kf5-kservice-devel
    - kf5-kiconthemes-devel
    - kf5-kwindowsystem-devel
    - kf5-kxmlgui-devel
    - kf5-kdbusaddons-devel
    - kf5-kconfig-devel
    - kf5-khtml-devel
    - kf5-kdelibs4support-devel
PkgConfigBR:
    - Qt5Core
    - Qt5DBus
    - Qt5Xml
    - Qt5Network
    - Qt5Gui
    - Qt5Widgets
    - Qt5Concurrent
    - Qt5Test
Requires:
    - kde5-filesystem

RequiresPost:
    - /sbin/ldconfig
RequiresPostUn:
    - /sbin/ldconfig

Files:
    - "%doc COPYING COPYING.DOC"
    - "%{_kde5_bindir}/systemsettings"
    - "%{_kde5_libdir}/libsystemsettingsview.so.*"
    - "%{_kde5_plugindir}/*.so"
    - "%{_kde5_datadir}/systemsettings"
    - "%{_datadir}/kservices5/*.desktop"
    - "%{_datadir}/kservicetypes5/*.desktop"
    - "%{_datadir}/applications/*.desktop"
    - "%{_datadir}/doc/HTML/en/systemsettings"

SubPackages:
    - Name: devel
      Group: Development/Libraries
      Summary: Development files for %{name}
      Description: |
        The %{name}-devel package contains the files necessary to develop applications
        that use %{name}.
      Files:
          - "%{_kde5_includedir}/systemsettingsview"
          - "%{_kde5_libdir}/libsystemsettingsview.so"
