Name         : systemsettings
Version      : 5.0.0
Release      : 1
Group        : System/Base
License      : GPLv2+
Summary      : KDE System Settings application
Description  : |
  KDE System Settings application
URL          : http://www.kde.org
SetupOptions : -q -n %{name}-%{version}/upstream

Sources:
    - "%{name}-%{version}.tar.xz"

RpmLintIgnore:
    - devel-file-in-non-devel-package
    - no-changelogname-tag
    - library-without-ldconfig-postin
    - library-without-ldconfig-postun

Configure    : none
Builder      : none

PkgBR:
    - kf5-rpm-macros
    - extra-cmake-modules
    - qt5-tools
    - kitemviews-devel
    - kcmutils-devel
    - ki18n-devel
    - kio-devel
    - kservice-devel
    - kiconthemes-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - kdbusaddons-devel
    - kconfig-devel
    - khtml-devel
    - kdelibs4support-devel
PkgConfigBR:
    - Qt5Core
    - Qt5DBus
    - Qt5Xml
    - Qt5Network
    - Qt5Gui
    - Qt5Widgets
    - Qt5Concurrent
    - Qt5Test
    - Qt5PrintSupport
Requires:
    - kf5-filesystem

RequiresPost:
    - /sbin/ldconfig
RequiresPostUn:
    - /sbin/ldconfig

Files:
    - "%doc COPYING COPYING.DOC"
    - "%{_kf5_bindir}/systemsettings5"
    - "%{_kf5_libdir}/libsystemsettingsview.so.*"
    - "%{_kf5_plugindir}/*"
    - "%{_kf5_sharedir}/systemsettings"
    - "%{_kf5_servicesdir}/*"
    - "%{_kf5_servicetypesdir}/*"
    - "%{_kf5_sharedir}/applications/*.desktop"
    - "%{_kf5_sharedir}/kxmlgui5/*"

SubPackages:
    - Name: devel
      Group: Development/Libraries
      Summary: Development files for %{name}
      Description: |
        The %{name}-devel package contains the files necessary to develop applications
        that use %{name}.
      Files:
          - "%{_includedir}/systemsettingsview"
          - "%{_kf5_libdir}/libsystemsettingsview.so"
    - Name: doc
      Group: Documentation
      Summary: Documentation and user manuals for %{name}
      Description: |
        Documentation and user manuals for %{name}
      Files:
          - "%{_kf5_htmldir}/en/systemsettings"
